language: ruby
rvm:
  - "2.1.1"
branches:
  only:
    - master
install: gem install rake && gem install github-pages && gem install s3_website && gem install jekyll && gem install therubyracer && gem install nokogiri
script: jekyll build
after_success: s3_website push
