defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

parentsite: https://www.bhashkar.me
permalink: /:title/
plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-gist', 'jekyll-feed', 'jemoji']
exclude: ['config.rb', 'README.md']

theme: jekyll-theme-minimal
sass:
  load_paths:
    - assets/_scss
  style: :compressed

title: Bhashkar Sharma
description: Personal Website.
repository: bhashkarsharma/bhashkarsharma.github.io
author:
  firstName: Bhashkar
  lastName: Sharma