defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

parentsite: https://www.bhashkar.me
permalink: /blog/:title/

collections:
  lists:
    output: true
  lab:
    output: true

plugins:
  - 'jekyll-paginate'
  - 'jekyll-sitemap'
  - 'jekyll-gist'
  - 'jekyll-feed'
  - 'jemoji'
  - 'jekyll-redirect-from'

exclude: 
  - 'config.rb'
  - 'README.md'
  - 'package.json'
  - 'package-lock.json'
  - 'node_modules'
  - 'scripts'
  - 'webpack'

theme: jekyll-theme-minimal
sass:
  load_paths:
    - assets/
  style: :compressed

title: Bhashkar Sharma
description: Personal Website.
repository: bhashkarsharma/bhashkarsharma.github.io
author:
  firstName: Bhashkar
  lastName: Sharma
